# BUILDER_IMAGE_TAG should identify the builder image
ARG BUILDER_IMAGE_TAG

# AVALANCHEGO_NODE_IMAGE needs to identify an existing avalanchego node image and should include the tag
ARG AVALANCHEGO_NODE_IMAGE

# ============= Compilation Stage ================
FROM antithesis-subnet-evm-builder:$BUILDER_IMAGE_TAG AS builder

# The builder workdir will vary between instrumented and non-instrumented builders
ARG BUILDER_WORKDIR

WORKDIR $BUILDER_WORKDIR

# Build the workload from unified test location
RUN go build -o ./build/antithesis-subnet-evm-workload \
    github.com/ava-labs/avalanchego/tests/antithesis/subnet-evm

# ============= Cleanup Stage ================
# Base the workflow on the node image to support bootstrap testing
FROM $AVALANCHEGO_NODE_IMAGE AS execution

# The builder workdir will vary between instrumented and non-instrumented builders
ARG BUILDER_WORKDIR

# Copy the executable into the container
COPY --from=builder $BUILDER_WORKDIR/build/antithesis-subnet-evm-workload ./workload

CMD [ "./workload" ]
