FROM scratch AS execution

# Copy config artifacts from the build path. For simplicity, artifacts
# are built outside of the docker image.
# Note: Context is repo root, paths relative to root
COPY  ./build/antithesis/subnet-evm/docker-compose.yml /
COPY  ./build/antithesis/subnet-evm/volumes /volumes
