// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: sync/sync.proto

package sync

import (
	merkledb "github.com/ava-labs/avalanchego/proto/pb/merkledb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request represents a request for information during syncing.
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*Request_RangeProofRequest
	//	*Request_ChangeProofRequest
	Message isRequest_Message `protobuf_oneof:"message"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_sync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{0}
}

func (m *Request) GetMessage() isRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *Request) GetRangeProofRequest() *merkledb.RangeProofRequest {
	if x, ok := x.GetMessage().(*Request_RangeProofRequest); ok {
		return x.RangeProofRequest
	}
	return nil
}

func (x *Request) GetChangeProofRequest() *merkledb.ChangeProofRequest {
	if x, ok := x.GetMessage().(*Request_ChangeProofRequest); ok {
		return x.ChangeProofRequest
	}
	return nil
}

type isRequest_Message interface {
	isRequest_Message()
}

type Request_RangeProofRequest struct {
	RangeProofRequest *merkledb.RangeProofRequest `protobuf:"bytes,1,opt,name=range_proof_request,json=rangeProofRequest,proto3,oneof"`
}

type Request_ChangeProofRequest struct {
	ChangeProofRequest *merkledb.ChangeProofRequest `protobuf:"bytes,2,opt,name=change_proof_request,json=changeProofRequest,proto3,oneof"`
}

func (*Request_RangeProofRequest) isRequest_Message() {}

func (*Request_ChangeProofRequest) isRequest_Message() {}

// ChangeProofResponse is the response for a ChangeProofRequest.
type ChangeProofResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*ChangeProofResponse_ChangeProof
	//	*ChangeProofResponse_RangeProof
	Response isChangeProofResponse_Response `protobuf_oneof:"response"`
}

func (x *ChangeProofResponse) Reset() {
	*x = ChangeProofResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sync_sync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeProofResponse) ProtoMessage() {}

func (x *ChangeProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_sync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeProofResponse.ProtoReflect.Descriptor instead.
func (*ChangeProofResponse) Descriptor() ([]byte, []int) {
	return file_sync_sync_proto_rawDescGZIP(), []int{1}
}

func (m *ChangeProofResponse) GetResponse() isChangeProofResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ChangeProofResponse) GetChangeProof() *merkledb.ChangeProof {
	if x, ok := x.GetResponse().(*ChangeProofResponse_ChangeProof); ok {
		return x.ChangeProof
	}
	return nil
}

func (x *ChangeProofResponse) GetRangeProof() *merkledb.RangeProof {
	if x, ok := x.GetResponse().(*ChangeProofResponse_RangeProof); ok {
		return x.RangeProof
	}
	return nil
}

type isChangeProofResponse_Response interface {
	isChangeProofResponse_Response()
}

type ChangeProofResponse_ChangeProof struct {
	ChangeProof *merkledb.ChangeProof `protobuf:"bytes,1,opt,name=change_proof,json=changeProof,proto3,oneof"`
}

type ChangeProofResponse_RangeProof struct {
	RangeProof *merkledb.RangeProof `protobuf:"bytes,2,opt,name=range_proof,json=rangeProof,proto3,oneof"`
}

func (*ChangeProofResponse_ChangeProof) isChangeProofResponse_Response() {}

func (*ChangeProofResponse_RangeProof) isChangeProofResponse_Response() {}

var File_sync_sync_proto protoreflect.FileDescriptor

var file_sync_sync_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x1a, 0x17, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x64,
	0x62, 0x2f, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb5, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4d, 0x0a, 0x13,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x65, 0x72, 0x6b,
	0x6c, 0x65, 0x64, 0x62, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x11, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x50,
	0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x50, 0x0a, 0x14, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x72, 0x6b,
	0x6c, 0x65, 0x64, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x12, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x96, 0x01, 0x0a, 0x13, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3a, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x64,
	0x62, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x48, 0x00, 0x52,
	0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x37, 0x0a, 0x0b,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x64, 0x62, 0x2e, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x76, 0x61, 0x2d, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x61, 0x76, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x68, 0x65, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x79,
	0x6e, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sync_sync_proto_rawDescOnce sync.Once
	file_sync_sync_proto_rawDescData = file_sync_sync_proto_rawDesc
)

func file_sync_sync_proto_rawDescGZIP() []byte {
	file_sync_sync_proto_rawDescOnce.Do(func() {
		file_sync_sync_proto_rawDescData = protoimpl.X.CompressGZIP(file_sync_sync_proto_rawDescData)
	})
	return file_sync_sync_proto_rawDescData
}

var file_sync_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sync_sync_proto_goTypes = []interface{}{
	(*Request)(nil),                     // 0: sync.Request
	(*ChangeProofResponse)(nil),         // 1: sync.ChangeProofResponse
	(*merkledb.RangeProofRequest)(nil),  // 2: merkledb.RangeProofRequest
	(*merkledb.ChangeProofRequest)(nil), // 3: merkledb.ChangeProofRequest
	(*merkledb.ChangeProof)(nil),        // 4: merkledb.ChangeProof
	(*merkledb.RangeProof)(nil),         // 5: merkledb.RangeProof
}
var file_sync_sync_proto_depIdxs = []int32{
	2, // 0: sync.Request.range_proof_request:type_name -> merkledb.RangeProofRequest
	3, // 1: sync.Request.change_proof_request:type_name -> merkledb.ChangeProofRequest
	4, // 2: sync.ChangeProofResponse.change_proof:type_name -> merkledb.ChangeProof
	5, // 3: sync.ChangeProofResponse.range_proof:type_name -> merkledb.RangeProof
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sync_sync_proto_init() }
func file_sync_sync_proto_init() {
	if File_sync_sync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sync_sync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sync_sync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeProofResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sync_sync_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Request_RangeProofRequest)(nil),
		(*Request_ChangeProofRequest)(nil),
	}
	file_sync_sync_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ChangeProofResponse_ChangeProof)(nil),
		(*ChangeProofResponse_RangeProof)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sync_sync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_sync_proto_goTypes,
		DependencyIndexes: file_sync_sync_proto_depIdxs,
		MessageInfos:      file_sync_sync_proto_msgTypes,
	}.Build()
	File_sync_sync_proto = out.File
	file_sync_sync_proto_rawDesc = nil
	file_sync_sync_proto_goTypes = nil
	file_sync_sync_proto_depIdxs = nil
}
