FROM scratch AS execution

# Copy config artifacts from the build path. For simplicity, artifacts
# are built outside of the docker image.
COPY  ./build/antithesis/docker-compose.yml /
COPY  ./build/antithesis/volumes /volumes
