FROM scratch AS execution

# Copy config artifacts from the build path. For simplicity, artifacts
# are built outside of the docker image.
# Note: Context is now the repo root, so paths are relative to that
COPY  ./graft/subnet-evm/build/antithesis/docker-compose.yml /
COPY  ./graft/subnet-evm/build/antithesis/volumes /volumes
