load("//.bazel:defs.bzl", "graft_go_test")

package(default_visibility = [
    "//graft/coreth:__subpackages__",
    "//graft/coreth:external_consumers",
])

graft_go_test(
    name = "corethgen_test",
    srcs = [
        "blocks_test.go",
        "generate_test.go",
        "rpccalls_test.go",
    ],
    deps = [
        "//chains/atomic",
        "//database",
        "//graft/coreth/core/extstate",
        "//graft/coreth/nativeasset",
        "//graft/coreth/params",
        "//graft/coreth/params/extras",
        "//graft/coreth/params/paramstest",
        "//graft/coreth/plugin/evm",
        "//graft/coreth/plugin/evm/atomic",
        "//graft/coreth/plugin/evm/atomic/vm",
        "//graft/coreth/plugin/evm/upgrade/ap0",
        "//graft/coreth/plugin/evm/upgrade/ap1",
        "//graft/coreth/plugin/evm/vmtest",
        "//graft/coreth/precompile/contracts/warp",
        "//graft/evm/constants",
        "//ids",
        "//snow",
        "//snow/engine/common",
        "//snow/engine/snowman/block",
        "//snow/validators",
        "//snow/validators/validatorstest",
        "//upgrade",
        "//upgrade/upgradetest",
        "//utils/constants",
        "//utils/crypto/bls/signer/localsigner",
        "//utils/units",
        "//vms/components/avax",
        "//vms/evm/predicate",
        "//vms/platformvm/warp",
        "//vms/platformvm/warp/payload",
        "//vms/saevm/cchain/synchronoustest",
        "//vms/saevm/cchain/warp/warptest",
        "//vms/saevm/saetest",
        "//vms/secp256k1fx",
        "@com_github_ava_labs_libevm//common",
        "@com_github_ava_labs_libevm//common/hexutil",
        "@com_github_ava_labs_libevm//core/types",
        "@com_github_ava_labs_libevm//core/vm",
        "@com_github_ava_labs_libevm//crypto",
        "@com_github_ava_labs_libevm//params",
        "@com_github_ava_labs_libevm//rlp",
        "@com_github_stretchr_testify//require",
    ],
)
