self-hosted-runner:
  labels:
    - avalanche-avalanchego-runner # Github Action Runner Controller
    - blacksmith-4vcpu-ubuntu-2404 # Beefier x86 runner
    - ubuntu-24.04-arm-4-core      # Beefier arm64 runner
