# TAG should identify the builder image
ARG TAG

# ============= Compilation Stage ================
FROM antithesis-avalanchego-builder:$TAG AS builder

# The workdir is hard-coded since this Dockerfile is only intended for instrumented builds.
WORKDIR /avalanchego_instrumented/customer

# Build avalanchego with race detection (-r) enabled.
RUN ./scripts/build.sh -r

# ============= Cleanup Stage ================
FROM debian:11-slim AS execution

# Copy identifying information into the container
COPY --from=builder /build/commit_hash.txt ./commit_hash.txt

# Copy the antithesis dependencies into the container
RUN mkdir -p /symbols
COPY --from=builder /avalanchego_instrumented/symbols /symbols
COPY --from=builder /opt/antithesis/lib/libvoidstar.so /usr/lib/libvoidstar.so

# Use the same path as the uninstrumented node image for consistency
WORKDIR /avalanchego/build

# Copy the executable into the container
COPY --from=builder /avalanchego_instrumented/customer/build/avalanchego ./avalanchego

CMD [ "./avalanchego" ]
