# TAG should identify the builder image
ARG TAG

# NODE_IMAGE needs to identify an existing node image and should include the tag
ARG NODE_IMAGE

# ============= Compilation Stage ================
FROM antithesis-avalanchego-builder:$TAG AS builder

# The builder workdir will vary between instrumented and non-instrumented builders
ARG BUILDER_WORKDIR

WORKDIR $BUILDER_WORKDIR

# Build the workload
RUN ./scripts/build_antithesis_avalanchego_workload.sh

# ============= Cleanup Stage ================
# Base the workflow on the node image to support bootstrap testing
FROM $NODE_IMAGE AS execution

# The builder workdir will vary between instrumented and non-instrumented builders
ARG BUILDER_WORKDIR

# Copy the executable into the container
COPY --from=builder $BUILDER_WORKDIR/build/antithesis-avalanchego-workload ./workload

CMD [ "./workload" ]
