load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("//.bazel:defs.bzl", "go_test")

package(default_visibility = [
    "//vms/saevm/cchain:__subpackages__",
    "//vms/saevm/cchain:external_consumers",
])

go_library(
    name = "state",
    srcs = [
        "bonus_blocks.go",
        "codec.go",
        "state.go",
        "syncer.go",
    ],
    embedsrcs = ["bonus_blocks.json"],
    importpath = "github.com/ava-labs/avalanchego/vms/saevm/cchain/state",
    deps = [
        "//chains/atomic",
        "//codec",
        "//codec/linearcodec",
        "//database",
        "//database/prefixdb",
        "//graft/coreth/plugin/evm/atomic/state",
        "//ids",
        "//network/p2p",
        "//snow",
        "//utils/constants",
        "//utils/set",
        "//utils/units",
        "//utils/wrappers",
        "//vms/evm/sync/hashdb",
        "//vms/saevm/cchain/tx",
        "//vms/saevm/types",
        "@com_github_ava_labs_libevm//common",
        "@com_github_ava_labs_libevm//core/types",
        "@com_github_ava_labs_libevm//trie",
        "@com_github_ava_labs_libevm//trie/trienode",
        "@com_github_ava_labs_libevm//triedb",
        "@com_github_ava_labs_libevm//triedb/hashdb",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "state_test",
    srcs = [
        "bonus_blocks_test.go",
        "state_test.go",
        "syncer_test.go",
    ],
    data = glob(["testdata/**"]),
    embed = [":state"],
    embedsrcs = ["bonus_block_consumers.json"],
    deps = [
        "//chains/atomic",
        "//database",
        "//database/memdb",
        "//database/prefixdb",
        "//database/versiondb",
        "//graft/coreth/ethclient",
        "//graft/coreth/plugin/evm",
        "//graft/coreth/plugin/evm/atomic",
        "//graft/coreth/plugin/evm/atomic/state",
        "//graft/coreth/plugin/evm/customtypes",
        "//ids",
        "//snow/snowtest",
        "//utils/constants",
        "//utils/logging",
        "//utils/logging/loggingtest",
        "//utils/set",
        "//vms/components/avax",
        "//vms/evm/sync/synctest",
        "//vms/saevm/cchain/tx",
        "//vms/saevm/cchain/tx/txtest",
        "//vms/saevm/saetest",
        "//vms/secp256k1fx",
        "//wallet/subnet/primary",
        "@com_github_ava_labs_libevm//common",
        "@com_github_ava_labs_libevm//core/types",
        "@com_github_ava_labs_libevm//libevm/options",
        "@com_github_google_go_cmp//cmp",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
