# Changes to the minimum golang version must also be replicated in
# tests/antithesis/Dockerfile.node
# tests/antithesis/Dockerfile.workload (here)
# Dockerfile
# README.md
# go.mod
# ============= Compilation Stage ================
FROM golang:1.21.9-bullseye AS builder

WORKDIR /build
# Copy and download avalanche dependencies using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy the code into the container
COPY . .

# Build the workload
RUN ./scripts/build_antithesis_workload.sh

# ============= Cleanup Stage ================
FROM debian:11-slim AS execution

# Copy the executable into the container
COPY --from=builder /build/build/workload ./workload

CMD [ "./workload" ]
