# The version is supplied as a build argument rather than hard-coded
# to minimize the cost of version changes.
ARG GO_VERSION

# ============= Compilation Stage ================
FROM golang:$GO_VERSION-bullseye AS builder

WORKDIR /build
# Copy and download avalanche dependencies using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy the code into the container
COPY . .

# Build the workload
RUN ./scripts/build_antithesis_workload.sh

# ============= Cleanup Stage ================
FROM debian:11-slim AS execution

# Copy the executable into the container
COPY --from=builder /build/build/workload ./workload

CMD [ "./workload" ]
