# The version is supplied as a build argument rather than hard-coded
# to minimize the cost of version changes.
ARG GO_VERSION=INVALID # This value isn't intended to be used but silences a warning

# Antithesis: Getting the Antithesis golang instrumentation library
FROM docker.io/antithesishq/go-instrumentor AS instrumentor

# ============= Instrumentation Stage ================
FROM golang:$GO_VERSION-bookworm

WORKDIR /build
# Copy and download dependencies using go mod
COPY go.mod .
COPY go.sum .
# Copy graft if it exists to support local replace directives
RUN --mount=type=bind,source=.,target=/context \
    if [ -d /context/graft ]; then cp -r /context/graft ./graft; fi
RUN go mod download

# Copy the code into the container
COPY . .

# Ensure pre-existing builds are not available for inclusion in the final image
RUN [ -d ./build ] && rm -rf ./build/* || true

# Keep the commit hash to easily verify the exact version that is running.
# Provided as a build arg so that VCS tooling is not required in the image.
ARG COMMIT_HASH=""
RUN echo "$COMMIT_HASH" > ./commit_hash.txt

# Copy the instrumentor and supporting files to their correct locations
COPY --from=instrumentor /opt/antithesis /opt/antithesis
COPY --from=instrumentor /opt/antithesis/lib /lib

# Create the destination output directory for the instrumented code
RUN mkdir -p /instrumented

# Instrument the code
RUN /opt/antithesis/bin/goinstrumentor \
    -stderrthreshold=INFO \
    -antithesis /opt/antithesis/instrumentation \
    . \
    /instrumented

WORKDIR /instrumented/customer
RUN go mod download
