// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/snow/networking/tracker (interfaces: Tracker)
//
// Generated by this command:
//
//	mockgen -package=trackermock -destination=snow/networking/tracker/trackermock/tracker.go -mock_names=Tracker=Tracker github.com/ava-labs/avalanchego/snow/networking/tracker Tracker
//

// Package trackermock is a generated GoMock package.
package trackermock

import (
	reflect "reflect"
	time "time"

	ids "github.com/ava-labs/avalanchego/ids"
	gomock "go.uber.org/mock/gomock"
)

// Tracker is a mock of Tracker interface.
type Tracker struct {
	ctrl     *gomock.Controller
	recorder *TrackerMockRecorder
}

// TrackerMockRecorder is the mock recorder for Tracker.
type TrackerMockRecorder struct {
	mock *Tracker
}

// NewTracker creates a new mock instance.
func NewTracker(ctrl *gomock.Controller) *Tracker {
	mock := &Tracker{ctrl: ctrl}
	mock.recorder = &TrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Tracker) EXPECT() *TrackerMockRecorder {
	return m.recorder
}

// TimeUntilUsage mocks base method.
func (m *Tracker) TimeUntilUsage(arg0 ids.NodeID, arg1 time.Time, arg2 float64) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimeUntilUsage", arg0, arg1, arg2)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// TimeUntilUsage indicates an expected call of TimeUntilUsage.
func (mr *TrackerMockRecorder) TimeUntilUsage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeUntilUsage", reflect.TypeOf((*Tracker)(nil).TimeUntilUsage), arg0, arg1, arg2)
}

// TotalUsage mocks base method.
func (m *Tracker) TotalUsage() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalUsage")
	ret0, _ := ret[0].(float64)
	return ret0
}

// TotalUsage indicates an expected call of TotalUsage.
func (mr *TrackerMockRecorder) TotalUsage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalUsage", reflect.TypeOf((*Tracker)(nil).TotalUsage))
}

// Usage mocks base method.
func (m *Tracker) Usage(arg0 ids.NodeID, arg1 time.Time) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usage", arg0, arg1)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Usage indicates an expected call of Usage.
func (mr *TrackerMockRecorder) Usage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usage", reflect.TypeOf((*Tracker)(nil).Usage), arg0, arg1)
}
