load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "paramstest",
    srcs = ["rules.go"],
    importpath = "github.com/ava-labs/avalanchego/graft/evm/params/paramstest",
    visibility = ["//visibility:public"],
    deps = [
        "//graft/evm/params",
        "//upgrade/upgradetest",
    ],
)
