load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "pchain",
    srcs = [
        "network.go",
        "staking.go",
        "vm.go",
    ],
    importpath = "github.com/ava-labs/avalanchego/tests/fixture/pchain",
    visibility = ["//visibility:public"],
    deps = [
        "//api/info",
        "//chains",
        "//chains/atomic",
        "//database",
        "//database/memdb",
        "//database/prefixdb",
        "//genesis",
        "//ids",
        "//snow",
        "//snow/consensus/snowman",
        "//snow/engine/common",
        "//snow/engine/enginetest",
        "//snow/snowtest",
        "//snow/uptime",
        "//snow/validators",
        "//tests",
        "//upgrade/upgradetest",
        "//utils/constants",
        "//utils/crypto/bls/signer/localsigner",
        "//utils/crypto/secp256k1",
        "//utils/json",
        "//utils/units",
        "//version",
        "//vms/platformvm",
        "//vms/platformvm/block/builder",
        "//vms/platformvm/config",
        "//vms/platformvm/fx",
        "//vms/platformvm/genesis/genesistest",
        "//vms/platformvm/platform",
        "//vms/platformvm/reward",
        "//vms/platformvm/signer",
        "//vms/platformvm/status",
        "//vms/secp256k1fx",
        "//wallet/chain/p/wallet",
        "//wallet/subnet/primary/common",
        "@com_github_gorilla_rpc//v2:rpc",
        "@com_github_stretchr_testify//require",
    ],
)
