// Code generated by Canoto. DO NOT EDIT.

package simplex

import (
	"unicode/utf8"

	"github.com/StephenButtolph/canoto"
)

// Ensure that "unicode/utf8" is imported without error
var _ = utf8.ValidString

const (
	canoto__CanotoVerifiedBlock__Metadata__tag = "\x0a" // canoto.Tag(1, canoto.Len)
	canoto__CanotoVerifiedBlock__InnerBlock__tag = "\x12" // canoto.Tag(2, canoto.Len)

	canoto__CanotoVerifiedBlock__Metadata__tag__size = len(canoto__CanotoVerifiedBlock__Metadata__tag)
	canoto__CanotoVerifiedBlock__InnerBlock__tag__size = len(canoto__CanotoVerifiedBlock__InnerBlock__tag)
)

type canotoData_CanotoVerifiedBlock struct {
}


func (c *CanotoVerifiedBlock) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(&r)
}

func (c *CanotoVerifiedBlock) UnmarshalCanotoFrom(r *canoto.Reader) error {
	var minField uint32
	for canoto.HasNext(r) {
		field, wireType, err := canoto.ReadTag(r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Len {
				return canoto.ErrInvalidWireType
			}
			c.Metadata, err = canoto.ReadBytes(r)
			if err != nil {
				return err
			}
			if len(c.Metadata) == 0 {
				return canoto.ErrZeroValue
			}
		case 2:
			if wireType != canoto.Len {
				return canoto.ErrInvalidWireType
			}
			c.InnerBlock, err = canoto.ReadBytes(r)
			if err != nil {
				return err
			}
			if len(c.InnerBlock) == 0 {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

func (c *CanotoVerifiedBlock) ValidCanoto() bool {
	return true
}

func (c *CanotoVerifiedBlock) SizeCanoto() int {
	var size int
	if len(c.Metadata) != 0 {
		size += canoto__CanotoVerifiedBlock__Metadata__tag__size + canoto.SizeBytes(c.Metadata)
	}
	if len(c.InnerBlock) != 0 {
		size += canoto__CanotoVerifiedBlock__InnerBlock__tag__size + canoto.SizeBytes(c.InnerBlock)
	}
	return size
}

func (c *CanotoVerifiedBlock) MarshalCanoto() []byte {
	w := canoto.Writer{
		B: make([]byte, 0, c.SizeCanoto()),
	}
	c.MarshalCanotoInto(&w)
	return w.B
}

func (c *CanotoVerifiedBlock) MarshalCanotoInto(w *canoto.Writer) {
	if len(c.Metadata) != 0 {
		canoto.Append(w, canoto__CanotoVerifiedBlock__Metadata__tag)
		canoto.AppendBytes(w, c.Metadata)
	}
	if len(c.InnerBlock) != 0 {
		canoto.Append(w, canoto__CanotoVerifiedBlock__InnerBlock__tag)
		canoto.AppendBytes(w, c.InnerBlock)
	}
}
