// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.17.1
// source: qc.go

package simplex

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__canotoQC__Sig__tag     = "\x0a" // canoto.Tag(1, canoto.Len)
	canoto__canotoQC__Signers__tag = "\x12" // canoto.Tag(2, canoto.Len)
)

type canotoData_canotoQC struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*canotoQC) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero canotoQC
	s := &canoto.Spec{
		Name: "canotoQC",
		Fields: []canoto.FieldType{
			{
				FieldNumber:    1,
				Name:           "Sig",
				OneOf:          "",
				TypeFixedBytes: uint64(len(zero.Sig)),
			},
			{
				FieldNumber: 2,
				Name:        "Signers",
				Repeated:    true,
				OneOf:       "",
				TypeBytes:   true,
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// MakeCanoto creates a new empty value.
func (*canotoQC) MakeCanoto() *canotoQC {
	return new(canotoQC)
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *canotoQC) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *canotoQC) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = canotoQC{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case 1:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			const (
				expectedLength       = len(c.Sig)
				expectedLengthUint64 = uint64(expectedLength)
			)
			var length uint64
			if err := canoto.ReadUint(&r, &length); err != nil {
				return err
			}
			if length != expectedLengthUint64 {
				return canoto.ErrInvalidLength
			}
			if expectedLength > len(r.B) {
				return io.ErrUnexpectedEOF
			}

			copy((&c.Sig)[:], r.B)
			if canoto.IsZero(c.Sig) {
				return canoto.ErrZeroValue
			}
			r.B = r.B[expectedLength:]
		case 2:
			if wireType != canoto.Len {
				return canoto.ErrUnexpectedWireType
			}

			// Skip the first entry because we have already stripped the tag.
			remainingBytes := r.B
			originalUnsafe := r.Unsafe
			r.Unsafe = true
			if err := canoto.ReadBytes(&r, new([]byte)); err != nil {
				return err
			}
			r.Unsafe = originalUnsafe

			// Count the number of additional entries after the first entry.
			countMinus1, err := canoto.CountBytes(r.B, canoto__canotoQC__Signers__tag)
			if err != nil {
				return err
			}
			c.Signers = canoto.MakeSlice(c.Signers, countMinus1+1)
			field := c.Signers

			// Read the first entry manually because the tag is still already
			// stripped.
			r.B = remainingBytes
			if err := canoto.ReadBytes(&r, &field[0]); err != nil {
				return err
			}

			// Read the rest of the entries, stripping the tag each time.
			field = field[1:]
			for i := range field {
				r.B = r.B[len(canoto__canotoQC__Signers__tag):]
				if err := canoto.ReadBytes(&r, &field[i]); err != nil {
					return err
				}
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *canotoQC) ValidCanoto() bool {
	if c == nil {
		return true
	}
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *canotoQC) CalculateCanotoCache() {
	if c == nil {
		return
	}
	var size uint64
	if !canoto.IsZero(c.Sig) {
		size += uint64(len(canoto__canotoQC__Sig__tag)) + canoto.SizeBytes((&c.Sig)[:])
	}
	for _, v := range c.Signers {
		size += uint64(len(canoto__canotoQC__Signers__tag)) + canoto.SizeBytes(v)
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *canotoQC) CachedCanotoSize() uint64 {
	if c == nil {
		return 0
	}
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *canotoQC) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *canotoQC) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if c == nil {
		return w
	}
	if !canoto.IsZero(c.Sig) {
		canoto.Append(&w, canoto__canotoQC__Sig__tag)
		canoto.AppendBytes(&w, (&c.Sig)[:])
	}
	for _, v := range c.Signers {
		canoto.Append(&w, canoto__canotoQC__Signers__tag)
		canoto.AppendBytes(&w, v)
	}
	return w
}
