name: Devcontainer CI

# ignore prs/commits that don't touch those files
on:
  pull_request:
    paths:
      - ".devcontainer/**"
  push:
    branches: [main]
    paths:
      - ".devcontainer/**"

jobs:
  build:
    name: Build devcontainer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build devcontainer
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5 # v0.3.1900000449
        with:
          runCmd: |
            set -x
            rustup show
            go version
            nix --version
            sccache --show-stats
            cargo nextest --version
            just --version
            gh --version
