name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    # Only cut releases from the canonical repo.
    if: github.repository == 'ava-labs/firewood'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # @v2
        with:
          draft: true
          generate_release_notes: true
