// Code generated by mockery v2.9.4. DO NOT EDIT.

package worker

import (
	mock "github.com/stretchr/testify/mock"
)

// Pool is an autogenerated mock type for the Pool type
type MockPool struct {
	mock.Mock
}

// Send provides a mock function with given fields: _a0
func (_m *MockPool) Send(_a0 Request) {
	_m.Called(_a0)
}

// Shutdown provides a mock function with given fields:
func (_m *MockPool) Shutdown() {
	_m.Called()
}
