// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.18.0
// source: config.go

package gastime

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 1
	_ uint = 1 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__GasPriceConfig__TargetToExcessScaling = 1
	canoto__GasPriceConfig__MinPrice              = 2
	canoto__GasPriceConfig__StaticPricing         = 3

	canoto__GasPriceConfig__TargetToExcessScaling__tag = "\x08" // canoto.Tag(canoto__GasPriceConfig__TargetToExcessScaling, canoto.Varint)
	canoto__GasPriceConfig__MinPrice__tag              = "\x10" // canoto.Tag(canoto__GasPriceConfig__MinPrice, canoto.Varint)
	canoto__GasPriceConfig__StaticPricing__tag         = "\x18" // canoto.Tag(canoto__GasPriceConfig__StaticPricing, canoto.Varint)
)

type canotoData_GasPriceConfig struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*GasPriceConfig) CanotoSpec(...reflect.Type) *canoto.Spec {
	var zero GasPriceConfig
	s := &canoto.Spec{
		Name: "GasPriceConfig",
		Fields: []canoto.FieldType{
			{
				FieldNumber: canoto__GasPriceConfig__TargetToExcessScaling,
				Name:        "TargetToExcessScaling",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.TargetToExcessScaling),
			},
			{
				FieldNumber: canoto__GasPriceConfig__MinPrice,
				Name:        "MinPrice",
				OneOf:       "",
				TypeUint:    canoto.SizeOf(zero.MinPrice),
			},
			{
				FieldNumber: canoto__GasPriceConfig__StaticPricing,
				Name:        "StaticPricing",
				OneOf:       "",
				TypeBool:    true,
			},
		},
	}
	s.CalculateCanotoCache()
	return s
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *GasPriceConfig) UnmarshalCanoto(bytes []byte) error {
	r := canoto.Reader{
		B: bytes,
	}
	return c.UnmarshalCanotoFrom(r)
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *GasPriceConfig) UnmarshalCanotoFrom(r canoto.Reader) error {
	// Zero the struct before unmarshaling.
	*c = GasPriceConfig{}
	atomic.StoreUint64(&c.canotoData.size, uint64(len(r.B)))

	var minField uint32
	for canoto.HasNext(&r) {
		field, wireType, err := canoto.ReadTag(&r)
		if err != nil {
			return err
		}
		if field < minField {
			return canoto.ErrInvalidFieldOrder
		}

		switch field {
		case canoto__GasPriceConfig__TargetToExcessScaling:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.TargetToExcessScaling); err != nil {
				return err
			}
			if canoto.IsZero(c.TargetToExcessScaling) {
				return canoto.ErrZeroValue
			}
		case canoto__GasPriceConfig__MinPrice:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadUint(&r, &c.MinPrice); err != nil {
				return err
			}
			if canoto.IsZero(c.MinPrice) {
				return canoto.ErrZeroValue
			}
		case canoto__GasPriceConfig__StaticPricing:
			if wireType != canoto.Varint {
				return canoto.ErrUnexpectedWireType
			}

			if err := canoto.ReadBool(&r, &c.StaticPricing); err != nil {
				return err
			}
			if canoto.IsZero(c.StaticPricing) {
				return canoto.ErrZeroValue
			}
		default:
			return canoto.ErrUnknownField
		}

		minField = field + 1
	}
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *GasPriceConfig) ValidCanoto() bool {
	return true
}

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *GasPriceConfig) CalculateCanotoCache() {
	var size uint64
	if !canoto.IsZero(c.TargetToExcessScaling) {
		size += uint64(len(canoto__GasPriceConfig__TargetToExcessScaling__tag)) + canoto.SizeUint(c.TargetToExcessScaling)
	}
	if !canoto.IsZero(c.MinPrice) {
		size += uint64(len(canoto__GasPriceConfig__MinPrice__tag)) + canoto.SizeUint(c.MinPrice)
	}
	if !canoto.IsZero(c.StaticPricing) {
		size += uint64(len(canoto__GasPriceConfig__StaticPricing__tag)) + canoto.SizeBool
	}
	atomic.StoreUint64(&c.canotoData.size, size)
}

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *GasPriceConfig) CachedCanotoSize() uint64 {
	return atomic.LoadUint64(&c.canotoData.size)
}

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *GasPriceConfig) MarshalCanoto() []byte {
	c.CalculateCanotoCache()
	w := canoto.Writer{
		B: make([]byte, 0, c.CachedCanotoSize()),
	}
	w = c.MarshalCanotoInto(w)
	return w.B
}

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *GasPriceConfig) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	if !canoto.IsZero(c.TargetToExcessScaling) {
		canoto.Append(&w, canoto__GasPriceConfig__TargetToExcessScaling__tag)
		canoto.AppendUint(&w, c.TargetToExcessScaling)
	}
	if !canoto.IsZero(c.MinPrice) {
		canoto.Append(&w, canoto__GasPriceConfig__MinPrice__tag)
		canoto.AppendUint(&w, c.MinPrice)
	}
	if !canoto.IsZero(c.StaticPricing) {
		canoto.Append(&w, canoto__GasPriceConfig__StaticPricing__tag)
		canoto.AppendBool(&w, true)
	}
	return w
}
