// Copyright (C) 2019, Ava Labs, Inc. All rights reserved.
// See the file LICENSE for licensing terms.

// Package upgradechaintest provides a deterministic, pre-generated C-Chain
// history crossing every scheduled network upgrade, for tests that need
// realistic synchronous blocks and state; e.g. tests of the coreth-to-SAE
// transition.
//
// The fixture is generated by TestFixtureUpToDate: a full coreth VM
// activates each upgrade at a distinct timestamp and accepts at least one
// block per upgrade exercising an observable change of that upgrade. The
// generator then dumps every accepted block and the VM's entire database.
//
//go:generate go test -run TestFixtureUpToDate -update .
package upgradechaintest

import (
	"encoding/json"
	"slices"
	"testing"
	"time"

	"github.com/ava-labs/libevm/common"
	"github.com/ava-labs/libevm/common/hexutil"
	"github.com/ava-labs/libevm/core"
	"github.com/ava-labs/libevm/core/types"
	"github.com/ava-labs/libevm/rlp"
	"github.com/stretchr/testify/require"

	_ "embed"

	"github.com/ava-labs/avalanchego/database"
	"github.com/ava-labs/avalanchego/ids"
	"github.com/ava-labs/avalanchego/upgrade"
)

// A Fixture is a complete, deterministic C-Chain history.
type Fixture struct {
	// Genesis is the JSON-encoded core.Genesis passed to the VM's
	// Initialize method.
	Genesis json.RawMessage `json:"genesis"`
	// Upgrades is the [upgrade.Config] the chain was generated with.
	// Upgrades after the tip's (Helicon onwards) are unscheduled.
	Upgrades upgrade.Config `json:"upgrades"`
	// ANTAssetID is the Avalanche-native-token asset ID imported in block 6
	// and moved by the fixture's nativeAssetCall transactions.
	ANTAssetID ids.ID `json:"antAssetID"`
	// Counter is the address of the fixture's counter contract, deployed in
	// block 1. A transaction (or eth_call) with empty call data increments
	// its storage slot 0; non-empty call data returns the slot's value as a
	// 32-byte word.
	Counter common.Address `json:"counter"`
	// Blocks holds the genesis block followed by every accepted block, in
	// height order, starting at height 0.
	Blocks []Block `json:"blocks"`
	// Database holds every key-value pair of the VM's database after all
	// Blocks were accepted, keyed by the hex-encoded key. Written verbatim
	// to an empty database, they recreate the state a coreth node would
	// hand to its successor VM.
	Database map[string]hexutil.Bytes `json:"database"`
}

//go:embed testdata/upgradechain_fixture.json
var fixtureJSON []byte

// Load returns the committed fixture.
func Load(tb testing.TB) *Fixture {
	tb.Helper()

	fx := new(Fixture)
	require.NoError(tb, json.Unmarshal(fixtureJSON, fx), "unmarshalling committed fixture")
	return fx
}

// Tip returns the fixture's highest block.
func (f *Fixture) Tip() Block {
	return f.Blocks[len(f.Blocks)-1]
}

// CoreGenesis decodes [Fixture.Genesis].
func (f *Fixture) CoreGenesis(tb testing.TB) core.Genesis {
	tb.Helper()

	var genesis core.Genesis
	require.NoError(tb, json.Unmarshal(f.Genesis, &genesis), "unmarshalling fixture genesis")
	return genesis
}

// SeedDatabase writes every [Fixture.Database] key-value pair to db,
// recreating the database a coreth node would hand to its successor VM.
func (f *Fixture) SeedDatabase(tb testing.TB, db database.KeyValueWriter) {
	tb.Helper()

	for keyHex, value := range f.Database {
		key, err := hexutil.Decode(keyHex)
		require.NoError(tb, err, "decoding fixture database key %s", keyHex)
		require.NoError(tb, db.Put(key, value), "seeding fixture database key %s", keyHex)
	}
}

// A Block is a single accepted block of the fixture chain.
type Block struct {
	// Fork names the network upgrade whose rules the block was built under.
	Fork string `json:"fork"`
	// Note describes what the block exercises.
	Note   string      `json:"note"`
	Number uint64      `json:"number"`
	Hash   common.Hash `json:"hash"`
	// Time is the block's timestamp in Unix seconds.
	Time uint64 `json:"time"`
	// RLP is the canonical encoding of the full block. Decoding it requires
	// the coreth libevm extras to be registered; see customtypes.Register.
	RLP hexutil.Bytes `json:"rlp"`
	// State holds the watched accounts' post-execution state as coreth
	// itself computed it, for asserting historical RPC results against.
	State map[common.Address]AccountState `json:"state"`
	// Counter is the value of the counter contract's storage slot 0 after
	// this block executed.
	Counter uint64 `json:"counterValue"`
	// IntermediateRoots holds the state root after each transaction, as
	// returned by debug_intermediateRoots. Nil for genesis, which is not
	// traceable.
	IntermediateRoots []common.Hash `json:"intermediateRoots,omitempty"`
}

// Timestamp returns [Block.Time] as a [time.Time].
func (b Block) Timestamp() time.Time {
	return time.Unix(int64(b.Time), 0) //#nosec G115 -- fixture timestamps are far below the int64 overflow boundary
}

// EthBlock decodes [Block.RLP]; the coreth libevm extras MUST be registered,
// as documented on that field.
func (b Block) EthBlock(tb testing.TB) *types.Block {
	tb.Helper()

	eth := new(types.Block)
	require.NoError(tb, rlp.DecodeBytes(b.RLP, eth), "rlp.DecodeBytes(block %d)", b.Number)
	return eth
}

// HasNativeAssetCall reports whether b is one of the
// [NativeAssetCallBlocks].
func (b Block) HasNativeAssetCall() bool {
	return slices.Contains(NativeAssetCallBlocks, b.Number)
}

// AccountState is the post-execution balance and nonce of an account.
type AccountState struct {
	Balance *hexutil.Big `json:"balance"`
	Nonce   uint64       `json:"nonce"`
	// ANTBalance is the account's multicoin balance of [Fixture.ANTAssetID].
	ANTBalance *hexutil.Big `json:"antBalance"`
}

// Heights ([Block.Number]) of fixture blocks that consuming tests single
// out. The generator asserts them, so they cannot silently drift.
var (
	// NativeAssetCallBlocks carry a functional nativeAssetCall, whose nested
	// EVM call makes tracing fail with [NativeAssetCallTraceError] — in
	// coreth and in any replaying VM.
	NativeAssetCallBlocks = []uint64{7, 11}

	// DeprecatedNativeAssetCallBlock's nativeAssetCall ran while the
	// precompile was deprecated, giving the fixture's only failed receipt.
	DeprecatedNativeAssetCallBlock uint64 = 10

	// SendWarpMessageBlock's sendWarpMessage logs the warp precompile's
	// SendWarpMessage event.
	SendWarpMessageBlock uint64 = 15
)

const (
	// NativeAssetCallTraceError is the exact error from the debug_trace*
	// endpoints on [NativeAssetCallBlocks].
	NativeAssetCallTraceError = "incorrect number of top-level calls"

	// GenesisTraceError is the exact error from the debug_trace* and
	// debug_intermediateRoots endpoints on the genesis block.
	GenesisTraceError = "genesis is not traceable"
)
