load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = [
    "//vms/saevm/cchain:__subpackages__",
    "//vms/saevm/cchain:external_consumers",
])

go_library(
    name = "libevm",
    srcs = [
        "hooks.go",
        "libevm.go",
    ],
    importpath = "github.com/ava-labs/avalanchego/vms/saevm/cchain/libevm",
    deps = [
        "//graft/coreth/params",
        "//vms/saevm/cchain/libevm/customtypes",
        "//vms/saevm/cchain/libevm/extstate",
        "@com_github_ava_labs_libevm//common",
        "@com_github_ava_labs_libevm//core/state",
        "@com_github_ava_labs_libevm//core/vm",
        "@com_github_ava_labs_libevm//libevm",
        "@com_github_ava_labs_libevm//libevm/stateconf",
    ],
)
