load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = [
    "//vms/saevm/cchain:__subpackages__",
    "//vms/saevm/cchain:external_consumers",
])

go_library(
    name = "libevm",
    srcs = ["libevm.go"],
    importpath = "github.com/ava-labs/avalanchego/vms/saevm/cchain/libevm",
    deps = [
        "//graft/coreth/core",
        "//graft/coreth/params",
        "//vms/saevm/cchain/extstate",
        "//vms/saevm/cchain/libevm/customtypes",
        "@com_github_ava_labs_libevm//libevm",
    ],
)
