load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("//.bazel:defs.bzl", "go_test")

go_library(
    name = "platform",
    srcs = [
        "block.go",
        "block_abort.go",
        "block_atomic.go",
        "block_commit.go",
        "block_common.go",
        "block_mock.go",
        "block_parse.go",
        "block_proposal.go",
        "block_standard.go",
        "block_visitor.go",
        "codec.go",
        "priorities.go",
        "subnet_validator.go",
        "tx.go",
        "tx_add_auto_renewed_validator.go",
        "tx_add_delegator.go",
        "tx_add_permissionless_delegator.go",
        "tx_add_permissionless_validator.go",
        "tx_add_subnet_validator.go",
        "tx_add_validator.go",
        "tx_advance_time.go",
        "tx_base.go",
        "tx_convert_subnet_to_l1.go",
        "tx_create_chain.go",
        "tx_create_subnet.go",
        "tx_disable_l1_validator.go",
        "tx_export.go",
        "tx_import.go",
        "tx_increase_l1_validator_balance.go",
        "tx_register_l1_validator.go",
        "tx_remove_subnet_validator.go",
        "tx_reward.go",
        "tx_reward_auto_renewed_validator.go",
        "tx_reward_validator.go",
        "tx_set_auto_renewed_validator_config.go",
        "tx_set_l1_validator_weight.go",
        "tx_staker.go",
        "tx_transfer_subnet_ownership.go",
        "tx_transform_subnet.go",
        "tx_unsigned.go",
        "tx_visitor.go",
        "validator.go",
    ],
    importpath = "github.com/ava-labs/avalanchego/vms/platformvm/platform",
    visibility = ["//visibility:public"],
    deps = [
        "//codec",
        "//codec/linearcodec",
        "//ids",
        "//network/p2p/gossip",
        "//snow",
        "//utils",
        "//utils/constants",
        "//utils/crypto/bls",
        "//utils/crypto/secp256k1",
        "//utils/hashing",
        "//utils/math",
        "//utils/set",
        "//utils/units",
        "//utils/wrappers",
        "//vms/components/avax",
        "//vms/components/verify",
        "//vms/platformvm/fx",
        "//vms/platformvm/reward",
        "//vms/platformvm/signer",
        "//vms/platformvm/stakeable",
        "//vms/platformvm/warp/message",
        "//vms/secp256k1fx",
        "//vms/types",
        "@org_uber_go_mock//gomock",
    ],
)

go_test(
    name = "platform_test",
    srcs = [
        "block_abort_test.go",
        "block_atomic_test.go",
        "block_commit_test.go",
        "block_mocks_generate_test.go",
        "block_parse_test.go",
        "block_proposal_test.go",
        "block_serialization_test.go",
        "block_standard_test.go",
        "priorities_test.go",
        "subnet_validator_test.go",
        "tx_add_auto_renewed_validator_test.go",
        "tx_add_delegator_test.go",
        "tx_add_permissionless_delegator_test.go",
        "tx_add_permissionless_validator_test.go",
        "tx_add_subnet_validator_test.go",
        "tx_add_validator_test.go",
        "tx_base_test.go",
        "tx_convert_subnet_to_l1_test.go",
        "tx_create_chain_test.go",
        "tx_disable_l1_validator_test.go",
        "tx_increase_l1_validator_balance_test.go",
        "tx_register_l1_validator_test.go",
        "tx_remove_subnet_validator_test.go",
        "tx_reward_auto_renewed_validator_test.go",
        "tx_set_auto_renewed_validator_config_test.go",
        "tx_set_l1_validator_weight_test.go",
        "tx_transfer_subnet_ownership_test.go",
        "tx_transform_subnet_test.go",
        "validator_test.go",
    ],
    embed = [":platform"],
    embedsrcs = [
        "tx_convert_subnet_to_l1_test_complex.json",
        "tx_convert_subnet_to_l1_test_simple.json",
        "tx_disable_l1_validator_test.json",
        "tx_increase_l1_validator_balance_test.json",
        "tx_register_l1_validator_test.json",
        "tx_set_l1_validator_weight_test.json",
    ],
    deps = [
        "//codec",
        "//ids",
        "//snow",
        "//snow/snowtest",
        "//utils",
        "//utils/constants",
        "//utils/crypto/bls",
        "//utils/crypto/bls/signer/localsigner",
        "//utils/crypto/secp256k1",
        "//utils/hashing",
        "//utils/math",
        "//utils/timer/mockable",
        "//utils/units",
        "//vms/components/avax",
        "//vms/components/avax/avaxmock",
        "//vms/components/verify",
        "//vms/components/verify/verifymock",
        "//vms/platformvm/fx/fxmock",
        "//vms/platformvm/reward",
        "//vms/platformvm/signer",
        "//vms/platformvm/stakeable",
        "//vms/platformvm/warp/message",
        "//vms/secp256k1fx",
        "//vms/types",
        "@com_github_stretchr_testify//require",
        "@org_uber_go_mock//gomock",
    ],
)
