# The version is supplied as a build argument rather than hard-coded
# to minimize the cost of version changes.
ARG GO_VERSION

# NODE_IMAGE needs to identify an existing node image and should include the tag
ARG NODE_IMAGE

# ============= Compilation Stage ================
FROM golang:$GO_VERSION-bullseye AS builder

WORKDIR /build
# Copy and download avalanche dependencies using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy the code into the container
COPY . .

# Build the workload
RUN ./scripts/build_antithesis_xsvm_workload.sh

# ============= Cleanup Stage ================
# Base the workflow on the node image to support bootstrap testing
FROM $NODE_IMAGE AS execution

# Copy the executable into the container
COPY --from=builder /build/build/antithesis-xsvm-workload ./workload

CMD [ "./workload" ]
