load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "cchainhelper",
    srcs = ["generate.go"],
    embedsrcs = [
        "CChainHelper.abi",
        "CChainHelper.bin",
    ],
    importpath = "github.com/ava-labs/avalanchego/tests/cchainhelper",
    visibility = ["//visibility:public"],
)
