# create an image from the local files
FROM golang:1.13.4-buster

RUN apt-get update && apt-get install -y libssl-dev libuv1-dev curl cmake

COPY .build_image_gopath $GOPATH/

WORKDIR $GOPATH/src/github.com/ava-labs/gecko

RUN ./scripts/build.sh
RUN ln -sv $GOPATH/src/github.com/ava-labs/gecko/ /gecko
