#!/usr/bin/env bash

set -euo pipefail

# Generates .patch files from BUILD files in .bazel/patches/build_files/.
#
# Each subdirectory of build_files/ corresponds to a module (matching the
# patch file naming convention). BUILD.bazel files within are diffed against
# /dev/null to produce patches that create new files.
#
# Why generate instead of hand-maintaining patches? Bazel's internal patch
# parser is stricter than `git apply` — hunk line counts in @@ headers must
# be exact. Generating from source BUILD files avoids counting errors.
#
# Why not use `diff -uN /dev/null`? Bazel expects git-style unified diffs
# with `diff --git` headers, `new file mode`, and no timestamps on ---/+++
# lines. `diff -uN` doesn't produce that format, so we'd need sed fixups
# for the headers and timestamps — roughly the same complexity as building
# the patch directly.
#
# Patches that modify existing files (e.g., gnark-crypto's no-sandbox tag)
# are maintained manually and are not generated by this script.
#
# See docs/bazel.md "Patch Maintenance" for the full procedure.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_FILES_DIR="${REPO_ROOT}/.bazel/patches/build_files"
PATCHES_DIR="${REPO_ROOT}/.bazel/patches"

for module_dir in "${BUILD_FILES_DIR}"/*/; do
  module_name="$(basename "${module_dir}")"
  patch_file="${PATCHES_DIR}/${module_name}.patch"

  # Collect all BUILD.bazel files relative to the module directory
  patch_content=""
  while IFS= read -r -d '' build_file; do
    rel_path="${build_file#"${module_dir}"}"
    # Generate a diff against /dev/null (new file)
    file_lines=$(wc -l < "${build_file}" | tr -d ' ')
    patch_content+="diff --git a/${rel_path} b/${rel_path}
new file mode 100644
--- /dev/null
+++ b/${rel_path}
@@ -0,0 +1,${file_lines} @@
"
    # Add each line with + prefix
    while IFS= read -r line || [[ -n "${line}" ]]; do
      patch_content+="+${line}
"
    done < "${build_file}"
  done < <(find "${module_dir}" -name 'BUILD.bazel' -print0 | sort -z)

  if [[ -n "${patch_content}" ]]; then
    printf '%s' "${patch_content}" > "${patch_file}"
    echo "Generated ${patch_file}"
  fi
done
