#!/usr/bin/env bash

set -euo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
  exit 0
fi

# The checked-in .bazelrc defaults macOS Bazel invocations to the default
# CommandLineTools installation path which is also used by GitHub Actions runners in
# CI. A local macOS host may have a different active Apple developer toolchain and
# this script can be used to generate a `.bazelrc.local` with host-specific overrides.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_PATH="${REPO_ROOT}/.bazelrc.local"

# Use the host's currently selected developer directory and macOS SDK so local
# bazel/bazelisk invocations use the correct Apple toolchain.
ERR_FILE="$(mktemp)"
trap 'rm -f "$ERR_FILE"' EXIT

if ! DEVELOPER_DIR="$(xcode-select -p 2>"$ERR_FILE")"; then
  echo "error: failed to determine the active Apple developer directory via xcode-select -p" >&2
  cat "$ERR_FILE" >&2
  echo "hint: install Apple CommandLineTools with 'xcode-select --install' or select an existing Xcode with 'sudo xcode-select -s /Applications/Xcode.app/Contents/Developer'" >&2
  exit 1
fi

if ! SDKROOT="$(xcrun --sdk macosx --show-sdk-path 2>"$ERR_FILE")"; then
  echo "error: failed to determine the macOS SDK path via xcrun --sdk macosx --show-sdk-path" >&2
  cat "$ERR_FILE" >&2
  echo "hint: install Apple CommandLineTools with 'xcode-select --install' or ensure the selected Xcode/CommandLineTools installation provides the macOS SDK" >&2
  exit 1
fi
SYSTEMROOT="$SDKROOT"

cat >"${OUT_PATH}" <<EOF
# Generated by scripts/generate_bazelrc_local.sh.
# Do not edit by hand.
build:macos --repo_env=DEVELOPER_DIR="${DEVELOPER_DIR}"
build:macos --repo_env=SYSTEMROOT="${SYSTEMROOT}"
build:macos --action_env=DEVELOPER_DIR="${DEVELOPER_DIR}"
build:macos --action_env=SDKROOT="${SDKROOT}"
EOF
