// Code generated by MockGen. DO NOT EDIT.
// Source: utils/logging/logger.go

// Package logging is a generated GoMock package.
package logging

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	zap "go.uber.org/zap"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// AssertDeferredNoError mocks base method.
func (m *MockLogger) AssertDeferredNoError(f func() error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssertDeferredNoError", f)
}

// AssertDeferredNoError indicates an expected call of AssertDeferredNoError.
func (mr *MockLoggerMockRecorder) AssertDeferredNoError(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssertDeferredNoError", reflect.TypeOf((*MockLogger)(nil).AssertDeferredNoError), f)
}

// AssertDeferredTrue mocks base method.
func (m *MockLogger) AssertDeferredTrue(f func() bool, format string, args ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []interface{}{f, format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AssertDeferredTrue", varargs...)
}

// AssertDeferredTrue indicates an expected call of AssertDeferredTrue.
func (mr *MockLoggerMockRecorder) AssertDeferredTrue(f, format interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{f, format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssertDeferredTrue", reflect.TypeOf((*MockLogger)(nil).AssertDeferredTrue), varargs...)
}

// AssertNoError mocks base method.
func (m *MockLogger) AssertNoError(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssertNoError", err)
}

// AssertNoError indicates an expected call of AssertNoError.
func (mr *MockLoggerMockRecorder) AssertNoError(err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssertNoError", reflect.TypeOf((*MockLogger)(nil).AssertNoError), err)
}

// AssertTrue mocks base method.
func (m *MockLogger) AssertTrue(b bool, format string, args ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []interface{}{b, format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AssertTrue", varargs...)
}

// AssertTrue indicates an expected call of AssertTrue.
func (mr *MockLoggerMockRecorder) AssertTrue(b, format interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{b, format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssertTrue", reflect.TypeOf((*MockLogger)(nil).AssertTrue), varargs...)
}

// Debug mocks base method.
func (m *MockLogger) Debug(format string, args ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(format interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), varargs...)
}

// Error mocks base method.
func (m *MockLogger) Error(format string, args ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(format interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), varargs...)
}

// Fatal mocks base method.
func (m *MockLogger) Fatal(format string, args ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatal", varargs...)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockLoggerMockRecorder) Fatal(format interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockLogger)(nil).Fatal), varargs...)
}

// Info mocks base method.
func (m *MockLogger) Info(format string, args ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(format interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), varargs...)
}

// RecoverAndExit mocks base method.
func (m *MockLogger) RecoverAndExit(f, exit func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecoverAndExit", f, exit)
}

// RecoverAndExit indicates an expected call of RecoverAndExit.
func (mr *MockLoggerMockRecorder) RecoverAndExit(f, exit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecoverAndExit", reflect.TypeOf((*MockLogger)(nil).RecoverAndExit), f, exit)
}

// RecoverAndPanic mocks base method.
func (m *MockLogger) RecoverAndPanic(f func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecoverAndPanic", f)
}

// RecoverAndPanic indicates an expected call of RecoverAndPanic.
func (mr *MockLoggerMockRecorder) RecoverAndPanic(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecoverAndPanic", reflect.TypeOf((*MockLogger)(nil).RecoverAndPanic), f)
}

// Stop mocks base method.
func (m *MockLogger) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockLoggerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockLogger)(nil).Stop))
}

// StopOnPanic mocks base method.
func (m *MockLogger) StopOnPanic() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopOnPanic")
}

// StopOnPanic indicates an expected call of StopOnPanic.
func (mr *MockLoggerMockRecorder) StopOnPanic() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopOnPanic", reflect.TypeOf((*MockLogger)(nil).StopOnPanic))
}

// Trace mocks base method.
func (m *MockLogger) Trace(format string, args ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Trace", varargs...)
}

// Trace indicates an expected call of Trace.
func (mr *MockLoggerMockRecorder) Trace(format interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trace", reflect.TypeOf((*MockLogger)(nil).Trace), varargs...)
}

// Verbo mocks base method.
func (m *MockLogger) Verbo(format string, args ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Verbo", varargs...)
}

// Verbo indicates an expected call of Verbo.
func (mr *MockLoggerMockRecorder) Verbo(format interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verbo", reflect.TypeOf((*MockLogger)(nil).Verbo), varargs...)
}

// Warn mocks base method.
func (m *MockLogger) Warn(format string, args ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []interface{}{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(format interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), varargs...)
}

// Write mocks base method.
func (m *MockLogger) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockLoggerMockRecorder) Write(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockLogger)(nil).Write), p)
}
