// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: messenger/messenger.proto

package messenger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message int32

const (
	Message_MESSAGE_UNSPECIFIED         Message = 0
	Message_MESSAGE_BUILD_BLOCK         Message = 1
	Message_MESSAGE_STATE_SYNC_FINISHED Message = 2
)

// Enum value maps for Message.
var (
	Message_name = map[int32]string{
		0: "MESSAGE_UNSPECIFIED",
		1: "MESSAGE_BUILD_BLOCK",
		2: "MESSAGE_STATE_SYNC_FINISHED",
	}
	Message_value = map[string]int32{
		"MESSAGE_UNSPECIFIED":         0,
		"MESSAGE_BUILD_BLOCK":         1,
		"MESSAGE_STATE_SYNC_FINISHED": 2,
	}
)

func (x Message) Enum() *Message {
	p := new(Message)
	*p = x
	return p
}

func (x Message) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message) Descriptor() protoreflect.EnumDescriptor {
	return file_messenger_messenger_proto_enumTypes[0].Descriptor()
}

func (Message) Type() protoreflect.EnumType {
	return &file_messenger_messenger_proto_enumTypes[0]
}

func (x Message) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message.Descriptor instead.
func (Message) EnumDescriptor() ([]byte, []int) {
	return file_messenger_messenger_proto_rawDescGZIP(), []int{0}
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       Message                `protobuf:"varint,1,opt,name=message,proto3,enum=messenger.Message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_messenger_messenger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_messenger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_messenger_messenger_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyRequest) GetMessage() Message {
	if x != nil {
		return x.Message
	}
	return Message_MESSAGE_UNSPECIFIED
}

type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_messenger_messenger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_messenger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_messenger_messenger_proto_rawDescGZIP(), []int{1}
}

var File_messenger_messenger_proto protoreflect.FileDescriptor

const file_messenger_messenger_proto_rawDesc = "" +
	"\n" +
	"\x19messenger/messenger.proto\x12\tmessenger\"=\n" +
	"\rNotifyRequest\x12,\n" +
	"\amessage\x18\x01 \x01(\x0e2\x12.messenger.MessageR\amessage\"\x10\n" +
	"\x0eNotifyResponse*\\\n" +
	"\aMessage\x12\x17\n" +
	"\x13MESSAGE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MESSAGE_BUILD_BLOCK\x10\x01\x12\x1f\n" +
	"\x1bMESSAGE_STATE_SYNC_FINISHED\x10\x022J\n" +
	"\tMessenger\x12=\n" +
	"\x06Notify\x12\x18.messenger.NotifyRequest\x1a\x19.messenger.NotifyResponseB4Z2github.com/ava-labs/avalanchego/proto/pb/messengerb\x06proto3"

var (
	file_messenger_messenger_proto_rawDescOnce sync.Once
	file_messenger_messenger_proto_rawDescData []byte
)

func file_messenger_messenger_proto_rawDescGZIP() []byte {
	file_messenger_messenger_proto_rawDescOnce.Do(func() {
		file_messenger_messenger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messenger_messenger_proto_rawDesc), len(file_messenger_messenger_proto_rawDesc)))
	})
	return file_messenger_messenger_proto_rawDescData
}

var file_messenger_messenger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messenger_messenger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_messenger_messenger_proto_goTypes = []any{
	(Message)(0),           // 0: messenger.Message
	(*NotifyRequest)(nil),  // 1: messenger.NotifyRequest
	(*NotifyResponse)(nil), // 2: messenger.NotifyResponse
}
var file_messenger_messenger_proto_depIdxs = []int32{
	0, // 0: messenger.NotifyRequest.message:type_name -> messenger.Message
	1, // 1: messenger.Messenger.Notify:input_type -> messenger.NotifyRequest
	2, // 2: messenger.Messenger.Notify:output_type -> messenger.NotifyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_messenger_messenger_proto_init() }
func file_messenger_messenger_proto_init() {
	if File_messenger_messenger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messenger_messenger_proto_rawDesc), len(file_messenger_messenger_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messenger_messenger_proto_goTypes,
		DependencyIndexes: file_messenger_messenger_proto_depIdxs,
		EnumInfos:         file_messenger_messenger_proto_enumTypes,
		MessageInfos:      file_messenger_messenger_proto_msgTypes,
	}.Build()
	File_messenger_messenger_proto = out.File
	file_messenger_messenger_proto_goTypes = nil
	file_messenger_messenger_proto_depIdxs = nil
}
