load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("//.bazel:defs.bzl", "go_test")

go_library(
    name = "network",
    srcs = ["network.go"],
    importpath = "github.com/ava-labs/avalanchego/vms/saevm/network",
    visibility = ["//visibility:public"],
    deps = [
        "//api/metrics",
        "//ids",
        "//network/p2p",
        "//snow",
        "//snow/engine/common",
        "//snow/validators",
        "//utils/set",
        "//version",
        "@com_github_ava_labs_libevm//libevm/options",
    ],
)

go_test(
    name = "network_test",
    srcs = ["network_test.go"],
    embed = [":network"],
    deps = [
        "//ids",
        "//snow/engine/enginetest",
        "//snow/snowtest",
        "//utils/set",
        "@com_github_stretchr_testify//require",
    ],
)
