load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = [
    "//graft/subnet-evm:__subpackages__",
    "//graft/subnet-evm:external_consumers",
])

go_library(
    name = "precompilebind",
    srcs = [
        "precompile_bind.go",
        "precompile_config_template.go",
        "precompile_contract_template.go",
        "precompile_event_template.go",
        "precompile_module_template.go",
    ],
    importpath = "github.com/ava-labs/avalanchego/graft/subnet-evm/accounts/abi/bind/precompilebind",
    deps = [
        "//graft/subnet-evm/accounts/abi/bind",
        "//graft/subnet-evm/accounts/abi/bind/precompilebind/templatetest",
        "//graft/subnet-evm/precompile/allowlist",
        "@com_github_ava_labs_libevm//accounts/abi",
    ],
)
