// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/vms/platformvm/txs (interfaces: PreContinuousStakingStaker)

// Package txs is a generated GoMock package.
package txs

import (
	reflect "reflect"
	time "time"

	ids "github.com/ava-labs/avalanchego/ids"
	bls "github.com/ava-labs/avalanchego/utils/crypto/bls"
	gomock "go.uber.org/mock/gomock"
)

// MockPreContinuousStakingStaker is a mock of PreContinuousStakingStaker interface.
type MockPreContinuousStakingStaker struct {
	ctrl     *gomock.Controller
	recorder *MockPreContinuousStakingStakerMockRecorder
}

// MockPreContinuousStakingStakerMockRecorder is the mock recorder for MockPreContinuousStakingStaker.
type MockPreContinuousStakingStakerMockRecorder struct {
	mock *MockPreContinuousStakingStaker
}

// NewMockPreContinuousStakingStaker creates a new mock instance.
func NewMockPreContinuousStakingStaker(ctrl *gomock.Controller) *MockPreContinuousStakingStaker {
	mock := &MockPreContinuousStakingStaker{ctrl: ctrl}
	mock.recorder = &MockPreContinuousStakingStakerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreContinuousStakingStaker) EXPECT() *MockPreContinuousStakingStakerMockRecorder {
	return m.recorder
}

// CurrentPriority mocks base method.
func (m *MockPreContinuousStakingStaker) CurrentPriority() Priority {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentPriority")
	ret0, _ := ret[0].(Priority)
	return ret0
}

// CurrentPriority indicates an expected call of CurrentPriority.
func (mr *MockPreContinuousStakingStakerMockRecorder) CurrentPriority() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentPriority", reflect.TypeOf((*MockPreContinuousStakingStaker)(nil).CurrentPriority))
}

// EndTime mocks base method.
func (m *MockPreContinuousStakingStaker) EndTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// EndTime indicates an expected call of EndTime.
func (mr *MockPreContinuousStakingStakerMockRecorder) EndTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndTime", reflect.TypeOf((*MockPreContinuousStakingStaker)(nil).EndTime))
}

// NodeID mocks base method.
func (m *MockPreContinuousStakingStaker) NodeID() ids.NodeID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NodeID")
	ret0, _ := ret[0].(ids.NodeID)
	return ret0
}

// NodeID indicates an expected call of NodeID.
func (mr *MockPreContinuousStakingStakerMockRecorder) NodeID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeID", reflect.TypeOf((*MockPreContinuousStakingStaker)(nil).NodeID))
}

// PendingPriority mocks base method.
func (m *MockPreContinuousStakingStaker) PendingPriority() Priority {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingPriority")
	ret0, _ := ret[0].(Priority)
	return ret0
}

// PendingPriority indicates an expected call of PendingPriority.
func (mr *MockPreContinuousStakingStakerMockRecorder) PendingPriority() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingPriority", reflect.TypeOf((*MockPreContinuousStakingStaker)(nil).PendingPriority))
}

// PublicKey mocks base method.
func (m *MockPreContinuousStakingStaker) PublicKey() (*bls.PublicKey, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicKey")
	ret0, _ := ret[0].(*bls.PublicKey)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PublicKey indicates an expected call of PublicKey.
func (mr *MockPreContinuousStakingStakerMockRecorder) PublicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicKey", reflect.TypeOf((*MockPreContinuousStakingStaker)(nil).PublicKey))
}

// StartTime mocks base method.
func (m *MockPreContinuousStakingStaker) StartTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// StartTime indicates an expected call of StartTime.
func (mr *MockPreContinuousStakingStakerMockRecorder) StartTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTime", reflect.TypeOf((*MockPreContinuousStakingStaker)(nil).StartTime))
}

// SubnetID mocks base method.
func (m *MockPreContinuousStakingStaker) SubnetID() ids.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubnetID")
	ret0, _ := ret[0].(ids.ID)
	return ret0
}

// SubnetID indicates an expected call of SubnetID.
func (mr *MockPreContinuousStakingStakerMockRecorder) SubnetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubnetID", reflect.TypeOf((*MockPreContinuousStakingStaker)(nil).SubnetID))
}

// Weight mocks base method.
func (m *MockPreContinuousStakingStaker) Weight() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Weight")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Weight indicates an expected call of Weight.
func (mr *MockPreContinuousStakingStakerMockRecorder) Weight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Weight", reflect.TypeOf((*MockPreContinuousStakingStaker)(nil).Weight))
}
