// Code generated by MockGen. DO NOT EDIT.
// Source: snow/networking/tracker/cpu_tracker.go

// Package mock_tracker is a generated GoMock package.
package tracker

import (
	reflect "reflect"
	time "time"

	ids "github.com/ava-labs/avalanchego/ids"
	gomock "github.com/golang/mock/gomock"
)

// MockTimeTracker is a mock of TimeTracker interface.
type MockTimeTracker struct {
	ctrl     *gomock.Controller
	recorder *MockTimeTrackerMockRecorder
}

// MockTimeTrackerMockRecorder is the mock recorder for MockTimeTracker.
type MockTimeTrackerMockRecorder struct {
	mock *MockTimeTracker
}

// NewMockTimeTracker creates a new mock instance.
func NewMockTimeTracker(ctrl *gomock.Controller) *MockTimeTracker {
	mock := &MockTimeTracker{ctrl: ctrl}
	mock.recorder = &MockTimeTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeTracker) EXPECT() *MockTimeTrackerMockRecorder {
	return m.recorder
}

// CumulativeUtilization mocks base method.
func (m *MockTimeTracker) CumulativeUtilization() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CumulativeUtilization")
	ret0, _ := ret[0].(float64)
	return ret0
}

// CumulativeUtilization indicates an expected call of CumulativeUtilization.
func (mr *MockTimeTrackerMockRecorder) CumulativeUtilization() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CumulativeUtilization", reflect.TypeOf((*MockTimeTracker)(nil).CumulativeUtilization))
}

// DecCPU mocks base method.
func (m *MockTimeTracker) DecCPU(arg0 ids.NodeID, arg1 time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DecCPU", arg0, arg1)
}

// DecCPU indicates an expected call of DecCPU.
func (mr *MockTimeTrackerMockRecorder) DecCPU(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecCPU", reflect.TypeOf((*MockTimeTracker)(nil).DecCPU), arg0, arg1)
}

// IncCPU mocks base method.
func (m *MockTimeTracker) IncCPU(arg0 ids.NodeID, arg1 time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncCPU", arg0, arg1)
}

// IncCPU indicates an expected call of IncCPU.
func (mr *MockTimeTrackerMockRecorder) IncCPU(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncCPU", reflect.TypeOf((*MockTimeTracker)(nil).IncCPU), arg0, arg1)
}

// TimeUntilUtilization mocks base method.
func (m *MockTimeTracker) TimeUntilUtilization(nodeID ids.NodeID, now time.Time, value float64) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimeUntilUtilization", nodeID, now, value)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// TimeUntilUtilization indicates an expected call of TimeUntilUtilization.
func (mr *MockTimeTrackerMockRecorder) TimeUntilUtilization(nodeID, now, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeUntilUtilization", reflect.TypeOf((*MockTimeTracker)(nil).TimeUntilUtilization), nodeID, now, value)
}

// Utilization mocks base method.
func (m *MockTimeTracker) Utilization(arg0 ids.NodeID, arg1 time.Time) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Utilization", arg0, arg1)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Utilization indicates an expected call of Utilization.
func (mr *MockTimeTrackerMockRecorder) Utilization(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Utilization", reflect.TypeOf((*MockTimeTracker)(nil).Utilization), arg0, arg1)
}
