name: buf-push

on:
  push:
    tags:
      - "*"
    branches:
      - master
      - dev
    paths:
      - "proto/**"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1.4.0
        with:
          input: "proto"
          # Breaking changes are managed by the rpcchainvm protocol version.
          breaking: false
          token: ${{ secrets.BUF_TOKEN }}
          # This version should match the version installed in the nix dev shell
          version: 1.47.2
