name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - master
      - dev

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish_docker_image:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU (required for cross-platform builds)
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4
      - name: Create multiplatform docker builder
        run: docker buildx create --use
      - name: Build and publish Docker images
        uses: ./.github/actions/run-docker-with-disk-space
        with:
          run: |
            DOCKER_IMAGE="$DOCKER_IMAGE_DEFAULT" scripts/run_task.sh build-image
            DOCKER_IMAGE=avaplatform/bootstrap-monitor scripts/run_task.sh build-bootstrap-monitor-image
            IMAGE_NAME=avaplatform/subnet-evm scripts/run_task.sh build-subnet-evm-image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_IMAGE_DEFAULT: ${{ secrets.DOCKER_REPO }}
          BUILD_MULTI_ARCH: 1
          PLATFORMS: "linux/amd64,linux/arm64"
          PUBLISH: 1
          ALLOW_TAG_LATEST: ${{ github.event_name != 'workflow_dispatch' }}
