name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - master
      - dev

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU (required for cross-platform builds)
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4
      - name: Create multiplatform docker builder
        run: docker buildx create --use
      - name: Build and publish images to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_REPO }}
          BUILD_MULTI_ARCH: 1
        run: scripts/run_task.sh build-image
      - name: Build and publish bootstrap-monitor image to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_IMAGE: avaplatform/bootstrap-monitor
          BUILD_MULTI_ARCH: 1
        run: scripts/run_task.sh build-bootstrap-monitor-image
      - name: Build and publish subnet-evm image to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          IMAGE_NAME: avaplatform/subnet-evm
          PLATFORMS: "linux/amd64,linux/arm64"
          PUBLISH: 1
          ALLOW_TAG_LATEST: ${{ github.event_name != 'workflow_dispatch' }}
        run: scripts/run_task.sh build-subnet-evm-image
