name: Publish Antithesis Images

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'The tag to apply to published images'
        default: latest
        required: true
        type: string
  push:
    branches:
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  REGISTRY: us-central1-docker.pkg.dev
  REPOSITORY: molten-verve-216720/avalanche-repository

jobs:
  antithesis:
    runs-on: ubuntu-24.04

    steps:
      - uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: false
          docker-images: true

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Login to GAR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ${{ env.REGISTRY }}
          username: _json_key
          password: ${{ secrets.ANTITHESIS_GAR_JSON_KEY }}

      - name: Build and push images for avalanchego test setup
        run: ./scripts/run_task.sh build-antithesis-images-avalanchego
        env:
          IMAGE_PREFIX: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag || 'latest' }}

      - name: Build and push images for xsvm test setup
        run: ./scripts/run_task.sh build-antithesis-images-xsvm
        env:
          IMAGE_PREFIX: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag || 'latest' }}

      - name: Build and push images for subnet-evm test setup
        run: ./scripts/run_task.sh build-antithesis-images-subnet-evm
        env:
          IMAGE_PREFIX: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag || 'latest' }}
