load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("//.bazel:defs.bzl", "go_test")

go_library(
    name = "c",
    srcs = [
        "backend.go",
        "builder.go",
        "builder_with_options.go",
        "context.go",
        "signer.go",
        "wallet.go",
        "wallet_with_options.go",
    ],
    importpath = "github.com/ava-labs/avalanchego/wallet/chain/c",
    visibility = ["//visibility:public"],
    deps = [
        "//api/info",
        "//database",
        "//graft/coreth/plugin/evm/atomic",
        "//ids",
        "//snow",
        "//utils",
        "//utils/constants",
        "//utils/crypto/keychain",
        "//utils/crypto/secp256k1",
        "//utils/logging",
        "//utils/math",
        "//utils/rpc",
        "//utils/set",
        "//vms/avm",
        "//vms/components/avax",
        "//vms/components/verify",
        "//vms/saevm/cchain",
        "//vms/saevm/cchain/tx",
        "//vms/secp256k1fx",
        "//wallet/subnet/primary/common",
        "@com_github_ava_labs_libevm//common",
        "@com_github_ava_labs_libevm//common/hexutil",
        "@com_github_ava_labs_libevm//ethclient",
    ],
)

go_test(
    name = "c_test",
    srcs = ["wallet_test.go"],
    embed = [":c"],
    deps = [
        "//ids",
        "//utils/rpc",
        "//vms/saevm/cchain/tx",
        "@com_github_stretchr_testify//require",
    ],
)
